// Copyright (c) 2025, NVIDIA CORPORATION.  All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package shared

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/template"

	"gopkg.in/yaml.v3"

	"github.com/NVIDIA/eidos/pkg/errors"
)

// IsSafePathComponent returns true if name is a single path component without
// any separators or parent directory references.
func IsSafePathComponent(name string) bool {
	if name == "" {
		return false
	}
	if strings.Contains(name, "/") || strings.Contains(name, "\\") {
		return false
	}
	if strings.Contains(name, "..") {
		return false
	}
	return true
}

// SafeJoin joins baseDir and name, then verifies the result is contained
// within baseDir. This prevents path traversal when name comes from
// untrusted input (e.g., component names from recipe data).
func SafeJoin(baseDir, name string) (string, error) {
	if filepath.IsAbs(name) {
		return "", errors.New(errors.ErrCodeInvalidRequest,
			fmt.Sprintf("path component %q is absolute and escapes base directory", name))
	}
	absBase, err := filepath.Abs(baseDir)
	if err != nil {
		return "", errors.Wrap(errors.ErrCodeInternal, "failed to resolve base directory", err)
	}
	joined := filepath.Clean(filepath.Join(absBase, name))
	if joined != absBase && !strings.HasPrefix(joined, absBase+string(filepath.Separator)) {
		return "", errors.New(errors.ErrCodeInvalidRequest,
			fmt.Sprintf("path component %q escapes base directory", name))
	}
	return joined, nil
}

// WriteValuesFile writes a values.yaml file with header comment to baseDir/filename.
// It uses SafeJoin to verify the output path stays within baseDir.
func WriteValuesFile(values map[string]any, baseDir, filename string) (string, int64, error) {
	outputPath, err := SafeJoin(baseDir, filename)
	if err != nil {
		return "", 0, err
	}

	var buf strings.Builder
	buf.WriteString("# Generated by Cloud Native Stack\n")
	buf.WriteString("---\n")

	if len(values) > 0 {
		yamlBytes, err := yaml.Marshal(values)
		if err != nil {
			return "", 0, errors.Wrap(errors.ErrCodeInternal, "failed to marshal values", err)
		}
		buf.Write(yamlBytes)
	}

	content := buf.String()
	if err := os.WriteFile(outputPath, []byte(content), 0600); err != nil {
		return "", 0, errors.Wrap(errors.ErrCodeInternal, "failed to write values file", err)
	}

	return outputPath, int64(len(content)), nil
}

// GenerateFromTemplate renders a template and writes it to baseDir/filename.
// It uses SafeJoin to verify the output path stays within baseDir.
func GenerateFromTemplate(tmplContent string, data any, baseDir, filename string) (string, int64, error) {
	outputPath, err := SafeJoin(baseDir, filename)
	if err != nil {
		return "", 0, err
	}

	tmpl, err := template.New("template").Parse(tmplContent)
	if err != nil {
		return "", 0, errors.Wrap(errors.ErrCodeInternal, "failed to parse template", err)
	}

	var buf strings.Builder
	if err := tmpl.Execute(&buf, data); err != nil {
		return "", 0, errors.Wrap(errors.ErrCodeInternal, "failed to execute template", err)
	}

	content := buf.String()
	if err := os.WriteFile(outputPath, []byte(content), 0600); err != nil {
		return "", 0, errors.Wrap(errors.ErrCodeInternal, "failed to write file", err)
	}

	return outputPath, int64(len(content)), nil
}
